export const statesCordinates = [
    { code: 'BC', name: 'Baja California', left: 50, top: 100, conections: ['BCS','SO']},
    { code: 'BCS', name: 'Baja California Sur', left: 150, top: 300 },
    { code: 'SO', name: 'Sonora', left: 250, top: 150, conections: ['CHI', 'SIN',] },
    { code: 'CHI', name: 'Chihuahua', left: 450, top: 200, conections: ['SIN', 'DU', 'CO'] },
    { code: 'SIN', name: 'Sinaloa', left: 400, top: 400, conections: ['DU', 'NA']},
    { code: 'DU', name: 'Durango', left: 550, top: 400, conections: ['CO','ZA','NA', 'JA'] },
    { code: 'CO', name: 'Coahuila', left: 650, top: 300, conections: ['NL', 'TAM','SL','ZA'] },
    { code: 'NA', name: 'Nayarit', left: 450, top: 570, conections: ['JA', 'ZA'] },
    { code: 'ZA', name: 'Zacatecas', left: 630, top: 500, conections: ['NL','SL','JA'] },
    { code: 'NL', name: 'Nuevo Leon', left: 770, top: 350, conections: ['TAM','SL','ZA','CO'] },
    { code: 'JA', name: 'Jalisco', left: 570, top: 650, conections: ['COL','MI','GUA'] },
    { code: 'COL', name: 'Colima', left: 550, top: 750, conections: ['MI'] },
    { code: 'MI', name: 'Michoacan', left: 680, top: 720, conections: ['GUA','GU'] },
    { code: 'GU', name: 'Guerrero', left: 750, top: 800, conections: ['OX','PU','MO']  },
    { code: 'OX', name: 'Oaxaca', left: 950, top: 850, conections: ['CH','VZ','PU'] },
    { code: 'CH', name: 'Chiapas', left: 1150, top: 850, conections: ['TA', 'VZ'] },
    { code: 'TA', name: 'Tabasco', left: 1140, top: 750, conections: ['VZ','CAM'] },
    { code: 'CAM', name: 'Campeche', left: 1250, top: 700, conections: ['YU','QR'] },
    { code: 'YU', name: 'Yucatan', left: 1350, top: 600, conections: ['QR'] },
    { code: 'QR', name: 'Quintana Roo', left: 1365, top: 700,  },
    { code: 'VZ', name: 'Veracruz', left: 950, top: 700, conections: ['PU', 'HI','SL','TAM'] },
    { code: 'PU', name: 'Puebla', left: 900, top: 770, size: 40, conections: ['TX','HI'] },
    { code: 'ME', name: 'Mexico', left: 800, top: 730, size: 40, conections: ['GU','MO', 'QU', 'PU', 'TX', 'MI', 'HI', 'GUA'] },
    { code: 'AC', name: 'Aguas Calientes', left: 620, top: 590, size: 40, conections: ['JA'] },
    { code: 'GUA', name: 'Guanajuato', left: 700, top: 600, conections: ['SL'] },
    { code: 'QU', name: 'Queretaro', left: 800, top: 650, size: 40, conections: ['HI', 'GUA','SL', 'MI'] },
    { code: 'HI', name: 'Hidalgo', left: 870, top: 670, size: 40, conections: ['SL'] },
    { code: 'MO', name: 'Morelos', left: 850, top: 770, size: 40 },
    { code: 'TX', name: 'Tlaxcala', left: 900, top: 720, size: 40},
    { code: 'TAM', name: 'Tamaulipas', left: 850, top: 450, conections: ['SL'] },
    { code: 'SL', name: 'San Luis Potosi', left: 750, top: 500, conections: [] }
  ]